version: "3.1"
# Config parameters for Kafka/Confluent Docker images:
# https://docs.confluent.io/current/installation/docker/config-reference.html
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:5.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # NOTE: PLAINTEXT not for real-data usage
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
