version: "3.1"
# Config parameters for Kafka/Confluent Docker images:
# https://docs.confluent.io/current/installation/docker/config-reference.html
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:5.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # NOTE: PLAINTEXT not for real-data usage
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  registry:
    image: confluentinc/cp-schema-registry:5.5.0
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
  rest-proxy:
    image: confluentinc/cp-kafka-rest:5.0.0
    depends_on:
      - zookeeper
      - kafka
      - registry
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://registry:8081
      KAFKA_REST_HOST_NAME: rest-proxy
  control-center:
    image: confluentinc/cp-enterprise-control-center:5.5.0
    depends_on:
      - zookeeper
      - kafka
      - registry
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:9092
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 2
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://registry:8081"